### ISSUE TITLE
Could you help using some open source license such as MIT or GPL?

### ISSUE THREAD

**Issue by cxwx** [ikalnytskyi/termcolor#46]
I'd love to add it to homebrew 
`https://github.com/Homebrew/homebrew-core/pull/57549`. 
But it has an license error

**Comment by ikalnytskyi** [comment]
Hey @cxwx! Can you please elaborate on a license error? `termcolor` is licensed under [BSD 3-clause License](https://choosealicense.com/licenses/bsd-3-clause/). It's an open source license and a lot of projects are using it.

**Comment by ikalnytskyi** [comment]
Ok, I checked the error message in your PR.

![image](https://user-images.githubusercontent.com/166626/86740450-546b1d00-c03f-11ea-9d61-b9615e6de196.png)

It seems like a license is not specified for the package. I assume that normally they have some sort of heuristic or something in Homebrew to autodetect the license based on LICENSE content. Due to some issue, though, they failed to do so. I bet if you explicitly specify the license in Homebrew's formula everything should be fine.

Example:

https://github.com/Homebrew/homebrew-core/blob/6a8f5692ae05d70f347ce194d9cd892370712239/Formula/udptunnel.rb#L7

**Comment by cxwx** [comment]
OK, thanks
