### ISSUE TITLE
#define min() and #define max() pollute global namespace by including termcolor.hpp

### ISSUE THREAD

**Issue by trailfrenzy** [ikalnytskyi/termcolor#47]
My work around was to **#undef min** and **#undef max** immediately after including termcolor.hpp.  The macro version of min and max smashed the **std::limits<>::min** and **std::limits<>::max**.  Is it possible to #undefine these two macros in termcolor.hpp since the min and max in now defined in #include <algorithm> which is the preferred way of using min() and max() for modern C++.

**Comment by jk-cx** [comment]
Same issue here with std::limits, 
#undef min
#undef max
solved it

**Comment by ikalnytskyi** [comment]
@trailfrenzy @jk-cx thanks for reporting that. Can you please confirm this issue is Windows specific?

**Comment by jk-cx** [comment]
@ikalnytskyi Can confirm the code compiles with #define NOMINMAX. Turns out this seems to be a common problem on Windows and is introduced by windows.h, see here: [https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std](url). Would be nice if you could mention it somewhere, other than that I think you are right, if you add the define it could lead to problems in some projects using the library

**Comment by ikalnytskyi** [comment]
Added this caveat to README. 

https://github.com/ikalnytskyi/termcolor/commit/fab28c507aa24b557c62a46ba7db611f531211f2
